baseURL: "https://dward.io/"
title: Bradley Camacho
paginate: 5
theme: PaperMod

params:
  defaultTheme: dark
  disableThemeToggle: false
  TocOpen: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  homeInfoParams:
      Title: Bradley Camacho
      Content: Tech writer - PDX
      imageUrl: https://github.com/bradleycamacho/dward.io/blob/main/static/profile.png?raw=true # optional
      imageTitle: "A photo of Bradley Camacho" # optional
      imageWidth: 244 # custom size
      imageHeight: 290 # cu
  socialIcons: # optional
    - name: github
      url: "https://github.com/bradleycamacho"
    - name: goodreads
      url: "https://www.goodreads.com/"
    - name: linkedin
      url: "https://www.linkedin.com/in/bradley-camacho/"
    - name: twitter
      url: "https://twitter.com/bradleyrcamacho"
markup:
  goldmark:
    renderer:
      unsafe: true